-- Company: 
-- Engineer: 
-- 
-- Create Date: 09.12.2024 16:58:39
-- Design Name: 
-- Module Name: String - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------

